# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd1faaf14e248181d6ece722fa682bb52257f5f74780db8ab23a13d5300d09001af57f964665def997525fa7d10b74d94caccf09203a90ba2ae1fa5668cf3efc

test:
  secret_key_base: 3c494ea279bde53096303cebe5d3c36f5fb866022394ecdb830abfcda8bc7c18cb520ede0bc342b2da95f127d1e86c0e118f01202f20a6b8d9b062f3cd3422e5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
